trigger:
- main
- feature/*
- issue/*

variables:
  ConnectionStrings__npgsql: "Server=localhost; Database=postgres; User Id=postgres; Password=root;"
  ConnectionStrings__sqlclient: "Server=(localdb)\\MSSQLLocalDB; Database=master; Integrated Security=true;"
  adapter: "sqlclient"
  ConnectionStrings__DefaultConnection: "server=(localdb)\\MSSQLLocalDB; database=base; Integrated Security=SSPI; TrustServerCertificate=True; Pooling=false"

stages:
- stage: Testing
  jobs:
  - job: Test
    timeoutInMinutes: 480

    pool:
      vmImage: 'windows-latest'

    strategy:
      matrix:
        dotnet_system:
          target: 'CiDotnetSystem'
        dotnet_system_database_adapters_memory:
          target: 'CiDotnetSystemDatabaseAdaptersMemory'
        dotnet_system_database_adapters_sqlclient:
          target: 'CiDotnetSystemDatabaseAdaptersSqlClient'
        dotnet_system_database_adapters_npgsql:
          target: 'CiDotnetSystemDatabaseAdaptersNpgsql'
        dotnet_system_workspace:
          target: 'CiDotnetSystemWorkspace'
        dotnet_system_workspace_adapters_direct:
          target: 'CiDotnetSystemWorkspaceAdaptersDirect'
        dotnet_system_workspace_adapters_json_newtonsoft:
          target: 'CiDotnetSystemWorkspaceAdaptersJsonNewtonsoft'
        dotnet_system_workspace_adapters_json_systemtext:
          target: 'CiDotnetSystemWorkspaceAdaptersJsonSystemText'
        dotnet_base_database:
          target: 'CiDotnetBaseDatabase'
        dotnet_base_workspace:
          target: 'CiDotnetBaseWorkspace'
        typescript_workspace:
          target: 'CiTypescriptWorkspace'
        typescript_workspace_adapters_json:
          target: 'CiTypescriptWorkspaceAdaptersJson'

    steps:
    - checkout: self
      submodules: true
    - powershell: Set-Culture -CultureInfo nl-BE
      displayName: CultureInfo nl-BE
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: 8.0.x
        includePreviewVersions: true
      displayName: 'Use .NET 8.0 sdk'
    - powershell: |
        ls $env:PGBIN
        Set-Service postgresql-x64-14 -StartupType manual
        Start-Service postgresql-x64-14
      displayName: 'Start PostgreSQL'
    - task: PowerShell@2
      env:
        NODE_OPTIONS: --max_old_space_size=16384
      inputs:
        targetType: 'filePath'
        filePath: 'build.ps1'
        arguments: -target $(target)
        failOnStderr: true
      displayName: Running $(target)
    - task: PublishTestResults@2
      condition: always()
      inputs:
        testRunTitle: $(target)
        testResultsFormat: 'VSTest'
        testResultsFiles: '*.trx'
        searchFolder: 'artifacts/tests'
      displayName: 'Results for $(target)'
